Takeoff.WebApp/Controllers/RootController.cs
using System;
using System.Net;
using System.Web.Mvc;

using Mediascend.Web;
using MvcContrib;
using System.Linq;
using Takeoff.Models;
using System.Web;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;
using System.Collections;
using System.Collections.Generic;
using Newtonsoft.Json;
using Takeoff.Resources;
using Takeoff.ViewModels;
namespace Takeoff.Controllers
{
    [RootUrl]
    [ExcludeFilter(typeof(CheckSuspendedAccountAttribute))]
    public class RootController : BasicController
    {

        /// <summary>
        /// The default page for the application
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(StartupMessage model)
        {
            //if the user came to the site for a new session and had their password saved in a cookie, we can expect that they'll want to go straight to their dashboard.  however, if they click on the app home page after being logged in, we let them go there
            if (this.IsLoggedIn() && (Request.UrlReferrer == null || (!Request.UrlReferrer.AbsoluteUri.StartsWith(ApplicationEx.AppUrlPrefix) && (!ApplicationEx.EnableHttps || !Request.UrlReferrer.AbsoluteUri.StartsWith(ApplicationEx.AppUrlPrefixSecure)))))
            {
                return this.RedirectToAction <DashboardController>(c => c.Index(null, null), UrlType.RelativeHttps);
            }

            //this is for the login portion of the page
            ViewData["redirectUrl"] = Url.Action<DashboardController>(c => c.Index(null, null), UrlType.RelativeHttps);
            ViewData["useAjaxPostForLogin"] = ApplicationEx.UseAjaxPostForLogin(Request);
            return View(model);
        }


        public ActionResult Gallery(string id)
        {
            ViewData["initialTab"] = id.HasChars() ? id.ToLowerInvariant() : "signup";
            return View();
        }

        public ActionResult Pricing()
        {
            var plans = this.Repository<Takeoff.Data.IPlansRepository>().GetPlansForSale().Select(p => new PlanForSale(p)).ToArray();
            return  this.View(plans);
        }

        public ActionResult UserAgreement()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult WhyVerify()
        {
            return View();
        }

        public ActionResult Privacy()
        {
            return View();
        }

        public ActionResult Try()
        {
            return View();
        }

        public ActionResult ThanksTo()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        /// <summary>
        /// Users are redirected here when they don't have cookies installed.
        /// </summary>
        /// <returns></returns>
        [ExcludeFilter(typeof(CheckCookiesAttribute))]
        public ActionResult NoCookies()
        {
            ViewData["CheckForCookies"] = null;//avoid an infinite redirect loop

            return View();
        }

        public ActionResult SendFileToSupport()
        {
            return View();
        }


    }
}

Takeoff.WebApp/Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Xml.Linq;
using Mediascend.Web;
using MvcContrib;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Recurly;
using Takeoff.Data;
using Takeoff.Models;
using Takeoff.Models.Data;
using Takeoff.Resources;
using Takeoff.ViewModels;

namespace Takeoff.Controllers
{

    public enum SignupType
    {
        StartTrial,
        Guest,
        TrialUserInfoRequested,
        DirectPurchase
    }

    /// <summary>
    /// Handles everything involved in signing up for a new account.
    /// </summary>
    public class SignupController : BasicController
    {
        private class PreventAlreadySignedUpUser : ActionFilterAttribute
        {
            public override void OnActionExecuting(ActionExecutingContext filterContext)
            {
                var user = filterContext.HttpContext.UserThing2();
                if (user != null)//users can't sign up twice, duh.  semi anonymous should be able to though
                {
                    filterContext.Result = new BadRequest
                    {
                        ErrorCode = ErrorCodes.UserCannotSignupBecauseTheyAreLoggedIn,
                        ErrorDescription = ErrorCodes.UserCannotSignupBecauseTheyAreLoggedInDescription,
                        ViewName = "AlreadySignedUp",
                    };
                }
            }
        }

        private ActionResult UserCannotSignupBecauseTheyAreLoggedIn()
        {
            return new BadRequest
            {
                ErrorCode = ErrorCodes.UserCannotSignupBecauseTheyAreLoggedIn,
                ErrorDescription = ErrorCodes.UserCannotSignupBecauseTheyAreLoggedInDescription,
                ViewName = "AlreadySignedUp",
            };
        }

        private bool UserHasNecessaryInfoForSubscription(IUser user)
        {
            return user.Email.HasChars();
        }

        /// <summary>
        /// Begins the signup process.  In this step, they select the plan they want to go with.
        /// </summary>
        /// <returns></returns>
        /// <param name="type"> </param>
        /// <param name="returnUrl"> </param>
        /// <param name="planId"> </param>
        /// <param name="postSignupUrl">The orignal url to redirect back to when the signup is complete.</param>
        /// <remarks>
        /// Client will be in 1 of these scenarions:
        /// - They are signed in under a demo account
        /// - They are brand new and clicked Signup
        /// - They were a guest (had a user but no account) and want to create an account
        /// </remarks>
        [HttpGet]
        public ActionResult Index(SignupType? type, string returnUrl, string planId)
        {
            var user = this.UserThing2();
            //if they came from the dashboard or wherever, use the referring url to go back to when we're done.  url must come from same host or else if they hit a /signup link from an email or something, it could take them back to google or wherever
            if (!returnUrl.HasChars() && Request.UrlReferrer != null && Request.Url != null && Request.Url.Host.EqualsCaseInsensitive(Request.UrlReferrer.Host))
                returnUrl = Request.UrlReferrer.OriginalString;

            if (!type.HasValue)
            {
                //do our best to automatically determine the signup type
                if (user != null)
                {
                    var account = user.Account;
                    if (account != null)
                    {
                        if (account.Status == AccountStatus.TrialAnonymous)
                        {
                            return View("Index-TrialUserInfoRequested", new Signup_Trial
                            {
                                ReturnUrl = returnUrl
                            });
                        }
                        else if ( account.Status == AccountStatus.Trial2)
                        {
                            return View("Subscribe-ChoosePlan");
                        }
                    }
                    else if (UserHasNecessaryInfoForSubscription(user))
                    {
                        return View("Subscribe-ChoosePlan");                        
                    }
                }
                if (user != null)
                    return UserCannotSignupBecauseTheyAreLoggedIn();
                return View("Index");
            }

            switch (type.Value)
            {
                case SignupType.Guest:
                    if (user != null)
                        return UserCannotSignupBecauseTheyAreLoggedIn();
                    return View("Guest");
                case SignupType.DirectPurchase:
                    if (user != null)
                        return UserCannotSignupBecauseTheyAreLoggedIn();
                    if (planId.HasChars())
                        return View("DirectPurchase", new Signup_DirectPurchase
                                                          {
                                                              PlanId = planId,                                                              
                                                          });
                    return View("DirectPurchase-ChoosePlan");
                case SignupType.TrialUserInfoRequested:
                    if (user == null)
                        return this.Login();
                    return View("Index-TrialUserInfoRequested", new Signup_Trial
                    {
                        ReturnUrl = returnUrl
                    });
                case SignupType.StartTrial:
                    if (user != null)
                        return UserCannotSignupBecauseTheyAreLoggedIn();
                    return View("Index");
                default:
                    return new BadRequest();
            }
        }

        /// <summary>
        /// Guest signup.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpParameterValue("type", "Guest", false)]
        [HttpPost]
        [PreventAlreadySignedUpUser]
        public ActionResult Create(Signup_Guest model)
        {
            //semi-anonymous users should be logged out at this point
            this.IdentityService().ClearIdentity(HttpContext);

            const string view = "Guest";

            var userRepository = this.Repository<IUsersRepository>();
            if (model.Email.HasChars())
            {
                switch (userRepository.GetExistanceByEmail(model.Email))
                {
                    case EntityExistance.Active:
                        ModelState.AddModelError(string.Empty, S.Signup_Account_EmailIsActive);
                        break;
                    case EntityExistance.Deleted:
                        ModelState.AddModelError(string.Empty, S.Signup_Account_EmailExistedButWasDeleted);
                        break;
                }
            }

            if (!ModelState.IsValid)
            {
                return this.Invalid(() => this.View(view));
            }

            var user = Users.Signup(model.Email, null, model.FirstName, model.LastName, model.TimezoneOffset, null, this.RequestDate(), model.Password);
            //log them in
            this.IdentityService().SetIdentity(new UserIdentity
            {
                UserId = user.Id
            }, IdentityPeristance.TemporaryCookie, HttpContext);

            this.LogBusinessEvent("GuestSignup", new
            {
            }, sendEmail: true);

            this.DeferRequest(Url.Action<EmailController>(c => c.SendUserSignup(user.Id)));

            return this.Success(() => View("Guest-Success"), null);
        }

        [HttpParameterValue("type", "StartTrial", false)]
        [HttpPost]
        [PreventAlreadySignedUpUser]
        public ActionResult Create(int? timezoneOffset)
        {
            var date = this.HttpContext.RequestDate();

            var user = Users.Signup(null, "You", null, null, timezoneOffset.GetValueOrDefault(), new { Type = "Trial" }, date);
            this.IdentityService().SetIdentity(new UserIdentity
            {
                UserId = user.Id
            }, IdentityPeristance.TemporaryCookie, HttpContext);

            //note this is also done in SettingsController.CreateAccount
            var account = Accounts.Create(user, TakeoffRoles.Owner, date, PlanIds.TrialAnonymous, AccountStatus.TrialAnonymous);

            this.LogBusinessEvent("TrialCreate", new
            {
                IsAnonymous = true,
            }, sendEmail: true);

            return this.Success(() => this.RedirectToAction(c => c.Sample()), new
            {
                UserId = user.Id,
            });

        }

        [HttpParameterValue("type", "TrialUserInfoRequested", false)]
        [HttpPost]
        [RestrictIdentity]
        public ActionResult Create(Signup_Trial model)
        {
            var user = this.UserThing2();
            var account = user.MapIfNotNull(u => u.Account);
            if (user == null || account == null || account.Status != AccountStatus.TrialAnonymous)
            {
                return new BadRequest
                {
                    ErrorCode = ErrorCodes.UserCannotSignupBecauseTheyAlreadyDid,
                    ErrorDescription = ErrorCodes.UserCannotSignupBecauseTheyAlreadyDidDescription,
                    ViewName = "LinkDoesNotApply",
                };
            }

            if (!ModelState.IsValid)
                return this.View("Index-TrialUserInfoRequested", model);
            var userRepository = this.Repository<IUsersRepository>();

Takeoff.WebApp/Views/Root/About.cshtml
@{
    Layout = "~/Views/Shared/Layout-External-Slim.cshtml";
    ViewData["PageTitle"] = "About";

}
@section JsDocReady
{
}
@section Header
{
	<h1>@("About Takeoff")</h1>
}
<section>
    <div class="page-header">
        <h2>@("Mission")</h2>
    </div>
    <p>@("Our goal is to make production easier for video creators and their clients by providing the best tool for review and approval.")</p>
</section>
<section>
    <div class="page-header">
        <h2>@("History")</h2>
    </div>
    <p>@("We were just a filmmaker and software developer who decided to do some video production.  During projects we struggled to get accurate feedback during post production.  So production took longer, we did extra rounds of edits, and our clients were frustrated.  We tried email, ftp, YouTube, Vimeo, and some other professional tools.  They were either insufficient, too complex, or too expensive.")</p>
    <p>@("So we built Takeoff in our spare time.  Our clients loved it.  Then we showed our producer buddies.  They all wanted their own account.  And it grew from there.  Now it's been a few years and thousands of people have used Takeoff.  We hope you fall in love with Takeoff too!")</p>
</section>
<section id="people">
    <div class="page-header">
        <h2>@("People")</h2>
    </div>
    <div class="person">        
        <h3>@("Stephen Potter, CEO")</h3>
        <img alt="@("Stephen Potter, CEO")" src="@this.Url.Asset("/Assets/img/about-steve.jpg")">
        <p>@("With decades of experience in software, Steve builds the systems behind Takeoff.  He also oversees business operations and determines company direction.")</p>
    </div>
    <div class="person">        
        <h3>@("Chris Kilayko, President")</h3>
        <img alt="@("Chris Kilayko, President")" src="@this.Url.Asset("/Assets/img/about-chris.jpg")">
        <p>@("Chris is a video expert and has done it all, from home movies all the way to producing live NBC newscasts.  Chris is responsible for customer service and for finding awesome video producers that could use Takeoff.")</p>
    </div>

</section>


Takeoff.WebApp/Views/Root/Contact.cshtml
@{
    Layout = "~/Views/Shared/Layout-External-Slim.cshtml";
    
    ViewData["PageTitle"] = "Contact Us";
}
@section JsDocReady
{
    $("#mainForm").madValidate({ useAjax: false }); 
    $("#timezoneOffset").val(new Date().getTimezoneOffset());
}
@section Header
{
	<h1>@("Contact Us")</h1>
}
<address>
    30 Spear St<br/>
    Metuchen, NJ 08840</br>
    (888) 551-2464
</address>

<dl class="dl-horizontal">
    <dt>@("Support")</dt>
    <dd><a href="mailto:support@takeoffvideo.com">support@takeoffvideo.com</a></dd>
    <dt>@("Sales")</dt>
    <dd><a href="mailto:sales@takeoffvideo.com">sales@takeoffvideo.com</a></dd>
    <dt>@("Stephen Potter, CEO")</dt>
    <dd><a href="mailto:stephenp@takeoffvideo.com">stephenp@takeoffvideo.com</a></dd>
    <dt>@("Chris Kilayko, President")</dt>
    <dd><a href="mailto:chrisk@takeoffvideo.com">chrisk@takeoffvideo.com</a></dd>
</dl>

Takeoff.WebApp/Views/Root/NoCookies.cshtml
@{
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml";
    
}
@section Header
{
    <h1>Please Enable Cookies</h1>
}
@section JsDocReady
{
   $("#back-button").click(function () {
        history.go(-1);
        return false;
    });
}
<p class="@Html.AlertErrorClass()">We need you to enable cookies in your browser in order to use Takeoff.</p>
<p>Cookies are small files on your computer that store settings like login information for various web sites.  Takeoff uses cookies and can't work without them.  Right now you don't have cookies enabled.  Enabling them is easy.  Check out <a href="http://www.google.com/support/accounts/bin/answer.py?&answer=61416" target="_blank">these instructions</a> from Google (who also uses cookies). </p>
<p>Once you have enabled cookies, please <a href="#" id="back-button">click here</a> to start using Takeoff.</p>
   

Takeoff.WebApp/Views/Root/SendFileToSupport.cshtml
@{
    Layout = "~/Views/Shared/Layout-External-Slim.cshtml";
    
}
@section Header
{
    <h1>Send Files to Takeoff Support</h1>
}

<iframe style="width: 640px; height: 400px; overflow: hidden" src="https://www.sendthisfile.com/filebox/index.jsp?widgetcode=pumkqqdxAWNCq1SAfHKh2J5P" marginwidth=0 marginheight=0 width="" height= scrolling="no" frameborder=0></iframe>

Takeoff.WebApp/Views/Root/ThanksTo.cshtml
@{
    Layout = "~/Views/Shared/Layout-External-Slim.cshtml";
    
    ViewData["PageTitle"] = "Thanks To";
}
@section JsDocReady
{
    $("#mainForm").madValidate({ useAjax: false }); 
    $("#timezoneOffset").val(new Date().getTimezoneOffset());
}
@section Header
{
	<h1>@("We Didn't do it Alone")</h1>
}
<p>
    @("Takeoff leverages some of the best companies and open source projects out there.  We love you all!")
</p>

<ul>
    <li><a href="http://zencoder.com" target="_blank">Zencoder</a> - handles all of Takeoff's video encoding.</li>
    <li><a href="http://aws.amazon.com" target="_blank">Amazon Web Services</a> - handles our file storage, message queueing, job servers, outgoing mail, data storage, caching, and content delivery.</li>
    <li><a href="http://softsyshosting.com" target="_blank">Softsys</a> - powers the mega awesome web server that runs Takeoff.</li>
    <li><a href="http://asp.net/mvc" target="_blank">.NET MVC</a> - the amazing web framework that Takeoff was built on.</li>
    <li><a href="http://cloudmailin.net" target="_blank">CloudmailIn</a> - processes incoming email for Takeoff.</li>
    <li><a href="http://postmarkapp.com" target="_blank">PostMark</a> - more outgoing email.</li>
    <li><a href="http://recurly.com" target="_blank">Recurly</a> - processes credit cards and handles recurring billing.</li>
    <li><a href="http://zendesk.com" target="_blank">Zendesk</a> - handles our support.</li>
    <li><a href="http://trello.com" target="_blank">Trello</a> - internal project management.</li>
    <li><a href="http://beanstalkapp.com" target="_blank">Beanstalk</a> - git and svn hosting.</li>
</ul>
<h3>Web Libraries</h3>
<ul>
    <li><a href="http://twitter.github.com/bootstrap/" target="_blank">Bootstrap</a> - provides the UI elements and some JS plugins we use to build our web app.</li>
    <li><a href="http://lesscss.org" target="_blank">LessCss</a> - CSS preprocessor that makes web dev a ton easier.</li>
    <li><a href="http://jquery.com" target="_blank">JQuery</a> - Makes UI scripting a cinch.</li>
    <li><a href="http://datejs.com" target="_blank">Date</a> - Date formatting and parsing for javascript.</li>
    <li><a href="http://swfupload.com" target="_blank">SWFUpload</a> - Flash-based file uploading.</li>
    <li><a href="http://datatables.new" target="_blank">DataTables</a> - awesome client-side data grid.</li>
    <li><a href="#" target="_blank">KeyFilter</a> - useful for filtering key entry into form fields.</li>
    <li><a href="http://docs.jquery.com/Plugins/Validation" target="_blank">Validate</a> - the best validation plugin ever made.</li>
    <li><a href="http://flesler.blogspot.com/2007/10/jqueryscrollto.html" target="_blank">ScrollTo</a> - scroll to an element automatically.</li>
    <li><a href="http://code.google.com/p/swfobject" target="_blank">SWFObject</a> - best way to embed Flash elements.</li>
</ul>
<h3>Server Libraries</h3>
<ul>
    <li><a href="#" target="_blank">Hammock</a> - easy way to communicate with REST interfaces in .net.</li>
    <li><a href="#" target="_blank">HTML Agility Pack</a> - used for our outgoing mail so we can turn typical markup into old school tables for email clients.</li>
    <li><a href="#" target="_blank">NewtonSoft JSON</a> - best JSON library out there.</li>
    <li><a href="#" target="_blank">Enyim Caching</a> - .net memcached client.</li>
    <li><a href="#" target="_blank">MVC mini profiler</a> - MVC mini profiler so our staff can monitor app performance in production.</li>
    <li><a href="#" target="_blank">Ninject</a> - Dependency injection, used to make various components pluggable.</li>
    <li><a href="#" target="_blank">Moq</a> - Mocking framework used for testing.</li>
</ul>
<h3>Our Open Source Projects</h3>
<p>We're open sourced some of the components we built for Takeoff.  And we plan on doing more of it.</p>
<ul>
    <li><a href="http://github.com/StevePotter/ArmChair" target="_blank">Armchair</a> - easily speeds up .net mvc apps by offloading certain tasks, like sending email or logging, to a different machine or process.</li>
    <li><a href="#" target="_blank">AssetBooster</a> - a build-time tool to minify, package, and upload static assets to a CDN.  Safer and more dev-friendly than dynamic packaging alternatives.</li>
    <li><a href="http://github.com/StevePotter/wetnap" target="_blank">Wetnap</a> - a collection of awesome .net extension methods that we feel should be built into the framework.</li>
    <li>Email Inliner (coming one day) - email clients suck with modern html standards.  This project lets you write html emails using regular css and elements like div, then transforms the document into a mail client-friendly format.  No more tables in your html email templates!</li>
    <li>Steps (coming one day) - helps .net jobs run better by splitting work into fault-tolerant 'steps' that are closely measured with killer reporting built in.</li>
    <li>Ripper (coming one day) - makes it possible to render mvc Razor views into static html files.  Awesome for QA, testing translations, and for designers who hate windows :).</li>
</ul>

Takeoff.WebApp/Views/Root/Try.cshtml
@{
    Layout = "~/Views/Shared/Layout-External-Slim.cshtml";
    
    ViewData["PageTitle"] = "Try";
}
@section JsDocReady
{
    $("#mainForm").madValidate({ useAjax: false }); 
    $("#timezoneOffset").val(new Date().getTimezoneOffset());
}
@section Header
{
	<h1>@S.Trial_PageHeading</h1>
}
<p class="instructions">
    @("Want to try Takeoff {0}without giving any personal information{/0}?  Then hit the button below, see if Takeoff is right for you, and sign up if and when you want.".FormatResource(Html.Element("strong")))
</p>

<div class="actions">
            <form method="post" action="@Url.Action("Create", "Signup", new { type = SignupType.StartTrial }, UrlType.RelativeHttps)">
                <input class="btn btn-large btn-primary" value="@("Try Takeoff Now")" type="submit" />
            </form>    
</div>


Takeoff.WebApp/Views/Root/WhyVerify.cshtml
@{
    Layout = "~/Views/Shared/Layout-App-Slim.cshtml";
    
    Html.ShowExternalLinksForVisitors();
    ViewData["PageTitle"] = "Why We Verify Your Email Address";
}

@section Header
{
  <h1>Why We Verify Your Email Address</h1>
}

    <p>We wanted to make it super easy to sign up for Takeoff.  When someone signs up for Takeoff, all we know is the email address that was entered. At that point we don’t know if the person really owns that email address. If we didn't verify this ownership, a mischievous person could cause some trouble.</p>
    <p>For example, without verification, a person could sign up under steve@gmail.com. But it's not Steve. It's Jon, Steve's evil nemesis. After signing up, Jon invites jodi@gmail.com. Jodi gets an email from Takeoff that says steve@gmail.com wants her to join a project. She accepts, because she works with Steve. In Takeoff, 'Steve' asks her to upload some files - private company documents. Jodi obliges. Jon gets those sensitive documents and laughs himself to sleep with thoughts of blackmail. </p>
    <p>We must prevent these situations, as rare as they are. So when someone claims to be steve@gmail.com, we must restrict what they can do until we know it is indeed them. This is a common practice among web sites. It's simple to do - just click on a link in an email we send. Some other web sites make you do this up front. We find that annoying, so we let people experience Takeoff right away and they can verify their email at their leisure. </p>