Takeoff.WebApp/Models/ViewModels/Staff_Plans.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.IO;
using Takeoff.Data;

namespace Takeoff.ViewModels
{
    public class Staff_Plans_Plan
    {
        public Staff_Plans_Plan()
        {
        }

        public Staff_Plans_Plan(IPlan data)
        {
            AllowSignups = data.AllowSignups;
            AssetFileSizeMax = data.AssetFileMaxSize;
            AssetsAllTimeMaxCount = data.AssetsAllTimeMaxCount;
            AssetsTotalMaxCount = data.AssetsTotalMaxCount;
            AssetsTotalSizeMax = data.AssetsTotalMaxSize;
            BillingIntervalLength = data.BillingIntervalLength;
            BillingIntervalUnit = data.BillingIntervalType.ToString();
            CreatedOn = data.CreatedOn;
            Title = data.Title;
            Notes = data.Notes;
            Id = data.Id;
            Price = data.PriceInCents/100.0;
            ProductionLimit = data.ProductionLimit;
            TrialIntervalLength = data.TrialIntervalLength;
            TrialIntervalUnit = data.TrialIntervalType.ToString();
            VideoFileSizeMax = data.VideoFileMaxSize;
            VideosTotalMaxCount = data.VideosTotalMaxCount;
            VideosPerBillingCycleMax = data.VideosPerBillingCycleMax;
            VideoDurationLimit = data.VideoDurationLimit;
        }

        [Required]
        [LocalizedDisplayName("AccountPlan_Model_Id")]
        public string Id { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_Title")]
        public string Title { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_CreatedOn")]
        public DateTime? CreatedOn { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_Description")]
        public string Notes { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_BillingInterval")]
        public int BillingIntervalLength { get; set; }

        public string BillingIntervalUnit { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_TrialInterval")]
        public int TrialIntervalLength { get; set; }

        public string TrialIntervalUnit { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_VideosTotalMaxCount")]
        public int? VideosTotalMaxCount { get; set; }

        public int? VideosPerBillingCycleMax { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_VideoFileSizeMax")]
        public FileSize? VideoFileSizeMax { get; set; }

        public int? VideoDurationLimit { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_AssetsTotalSizeMax")]
        public FileSize? AssetsTotalSizeMax { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_AssetsTotalMaxCount")]
        public int? AssetsTotalMaxCount { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_AssetsAllTimeMaxCount")]
        public int? AssetsAllTimeMaxCount { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_AssetFileSizeMax")]
        public FileSize? AssetFileSizeMax { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_ProductionLimit")]
        public int? ProductionLimit { get; set; }

        [LocalizedDisplayName("AccountPlan_Model_AllowSignups")]
        public bool AllowSignups { get; set; }

        // [ModelBinder(typeof(CurrencyModelBinder))]
        [LocalizedDisplayName("AccountPlan_Model_Price")]
        public double Price { get; set; }

        public void UpdateData(IPlan data)
        {
            data.AllowSignups = AllowSignups;
            data.AssetFileMaxSize = AssetFileSizeMax;
            data.AssetsAllTimeMaxCount = AssetsAllTimeMaxCount;
            data.AssetsTotalMaxCount = AssetsTotalMaxCount;
            data.AssetsTotalMaxSize = AssetsTotalSizeMax;
            data.BillingIntervalLength = BillingIntervalLength;
            data.BillingIntervalType = Enum<PlanInterval>.Parse(BillingIntervalUnit, false);
            if (CreatedOn.HasValue)
                data.CreatedOn = CreatedOn;
            if (Id.HasChars() && data.Id != Id)
                data.Id = Id;
            data.Title = Title;
            data.Notes = Notes;
            data.PriceInCents = (int) (Price*100);
            data.ProductionLimit = ProductionLimit;
            data.TrialIntervalLength = TrialIntervalLength;
            data.TrialIntervalType = Enum<PlanInterval>.Parse(TrialIntervalUnit, false);
            data.VideoFileMaxSize = VideoFileSizeMax;
            data.VideosTotalMaxCount = VideosTotalMaxCount;
            data.VideosPerBillingCycleMax = VideosPerBillingCycleMax;
            data.VideoDurationLimit = VideoDurationLimit;
        }
    }
}

Takeoff.WebApp/Controllers/Staff_PlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mediascend.Web;
using System.Web.Script.Serialization;
using System.Collections;
using Takeoff.Data;
using Takeoff.Models;
using Takeoff.Models.Data;
using System.Dynamic;
using MvcContrib;
using Takeoff.Transcoder;
using System.Configuration;
using Newtonsoft.Json.Linq;
using System.Web.UI.DataVisualization.Charting;
using System.Drawing;
using System.IO;
using System.Xml;
using System.Text;
using Takeoff.Resources;
using Recurly;
using System.Xml.Linq;
using Takeoff.ViewModels;
using System.Linq.Dynamic;
using System.ComponentModel;

namespace Takeoff.Controllers
{
    [SpecialRestriction(SpecialRestriction.Staff)]
    [SubController("/staff/plans", true)]
    public class Staff_PlansController : BasicController
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            ViewData["SectionTitle"] = "Plans";
        }

        public ActionResult Index()
        {
            ViewData.Model = Repos.Plans.Get();
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Staff_Plans_Plan
            {                
            });
        }
 
        [HttpPost]
        [ValidateJsonAntiForgeryToken()]
        public ActionResult Create(Staff_Plans_Plan model)
        {
            if (!ModelState.IsValid)
                return View(model);

            model.CreatedOn = this.RequestDate();

            var data = Repos.Plans.Insert(Repos.Plans.Instantiate().Once(model.UpdateData));
            if (!data.IsFree)
            {
                try
                {
                    CreateRecurlyPlan(data);
                }
                catch
                {
                    return View("SyncError");
                }
            }

            return this.RedirectToAction(c => c.Index());
        }

        public ActionResult Details(string id)
        {
            var data = Repos.Plans.Get(id);
            if (data == null)
                throw new ArgumentException("Plan with id '" + id + "' could not be found.");

            return View(new Staff_Plans_Plan(data));
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var data = Repos.Plans.Get(id);
            if (data == null)
                throw new ArgumentException("Plan with id '" + id + "' could not be found.");
            
            return View(new Staff_Plans_Plan(data));
        }

        /// <summary>
        /// todo: don't allow changing of id
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateJsonAntiForgeryToken()]
        public ActionResult Edit(Staff_Plans_Plan model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var data = Repos.Plans.Get(model.Id);
            model.UpdateData(data);
            Repos.Plans.Update(data);

            try
            {
                UpdateRecurlyPlan(data);
            }
            catch
            {
                return View("SyncError");
            }

            return this.RedirectToAction(c => c.Index());
        }


        [HttpPost]
        [ValidateJsonAntiForgeryToken()]
        public ActionResult Delete(string id)
        {
            var accountsWithPlan = DataModel.ReadOnlyQuery(db => db.Accounts.Where(a => a.PlanId == id).Count());
            if (accountsWithPlan > 0)
            {
                throw new InvalidOperationException(accountsWithPlan.ToInvariant() + " accounts currently use this plan.  You cannot delete a plan until no accounts use it.");
            }
            Repos.Plans.Delete(id);
            try
            {
                DeleteRecurlyPlan(id);
            }
            catch
            {
                return View("SyncError");
            }
  
            return this.RedirectToAction(c => c.Index());
        }


        [HttpGet]
        public ActionResult Sync()
        {
            return View();
        }

        /// <summary>
        /// Updates Recurly plans to match the plans in our database.
        /// </summary>
        /// <param name="planId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Sync(string planId)
        {
            IPlan[] recurlyPlans = null;
            RecurlyClient.PerformRequest(RecurlyClient.HttpRequestMethod.Get, "/company/plans", (reader) =>
            {
                recurlyPlans = XDocument.Load(reader).Descendants("plan").Select(e => FromRecurlyPlan(e)).ToArray();
            });


            recurlyPlans.SyncTo(Repos.Plans.Get(), p => p.Id, p => p.Id,
                (takeoffPlan, recurlyPlan) => ArePlansEqual(takeoffPlan, recurlyPlan), plansToAdd =>
                        {
                            //these plans were in db but not recurly.  the only trick here is that free plans don't go in recurly
                            plansToAdd.Where(p => !p.IsFree).Each(data =>
                                {
                                  CreateRecurlyPlan(data);
                                });
                        },
                        plansToDelete =>
                        {
                            //these plans are in recurly but not our db, so kill em!
                            plansToDelete.Each(data =>
                                {
                                    DeleteRecurlyPlan(data.Id);
                                });
                        }, plansToUpdate =>
                        {
                            plansToUpdate.Each(toUpdate =>
                            {
                                UpdateRecurlyPlan(toUpdate.Source);
                            });
                        }
                        );
            return this.Empty();
        }
        
        /// <summary>
        /// Calls the Recurly API to createa a new plan.
        /// </summary>
        /// <param name="data"></param>
        private void CreateRecurlyPlan(IPlan data)
        {

            XDocument xDoc = null;
            RecurlyClient.PerformRequest(RecurlyClient.HttpRequestMethod.Post, "/company/plans", (writer) =>
            {
                WriteRecurlyPlanXml(writer, data);
            }, (reader) =>
            {
                xDoc = XDocument.Load(reader);
            });
        }


        /// <summary>
        /// Deletes a plan from Recurly.
        /// </summary>
        /// <param name="id"></param>
        private static void DeleteRecurlyPlan(string id)
        {
            RecurlyClient.PerformRequest(RecurlyClient.HttpRequestMethod.Delete, "/company/plans/" + id);
        }

        /// <summary>
        /// Indicates whether the plans from Takeoff's DB and Recurly's API are equivalent.
        /// </summary>
        /// <param name="fromTakeoffDb"></param>
        /// <param name="fromRecurly"></param>
        /// <returns></returns>
        private static bool ArePlansEqual(IPlan fromTakeoffDb, IPlan fromRecurly)
        {
            return fromRecurly.Title.EqualsCaseSensitive(fromTakeoffDb.Title)
                    && fromRecurly.Notes.EqualsCaseSensitive(fromTakeoffDb.Notes)
                    && fromRecurly.PriceInCents == fromTakeoffDb.PriceInCents
                    && fromRecurly.BillingIntervalLength == fromTakeoffDb.BillingIntervalLength
                    && fromRecurly.BillingIntervalType == fromTakeoffDb.BillingIntervalType
                    && fromRecurly.TrialIntervalLength == fromTakeoffDb.TrialIntervalLength
                    && fromRecurly.TrialIntervalType == fromTakeoffDb.TrialIntervalType;
        }

        private void UpdateRecurlyPlan(IPlan data)
        {
            RecurlyClient.PerformRequest(RecurlyClient.HttpRequestMethod.Put, "/company/plans/" + data.Id, (writer) =>
            {
                WriteRecurlyPlanXml(writer, data);
            });
        }

        /// <summary>
        /// Creates a takeoff plan with the necessary properties from the Recurly plan taken from their API.
        /// </summary>
        /// <param name="recurlyPlan"></param>
        /// <returns></returns>
        static IPlan FromRecurlyPlan(XElement recurlyPlan)
        {
            return Repos.Plans.Instantiate().Once(p =>
                                                  {
                                                      p.Id = recurlyPlan.Element("plan_code").ValueOrDefault();
                                                      p.Title = recurlyPlan.Element("name").ValueOrDefault();
                                                      p.Notes = recurlyPlan.Element("description").ValueOrDefault();
                                                      p.PriceInCents =
                                                          recurlyPlan.Element("unit_amount_in_cents").ValueOrDefault
                                                              <int>();
                                                      p.BillingIntervalLength =
                                                          recurlyPlan.Element("plan_interval_length").ValueOrDefault
                                                              <int>();
                                                      p.BillingIntervalType =
                                                          Enum<PlanInterval>.Parse(
                                                              recurlyPlan.Element("plan_interval_unit").ValueOrDefault(),

Takeoff.WebApp/Views/Staff_Plans/Create.cshtml
@model Staff_Plans_Plan
@{
    Layout = "~/Views/Staff/staff-layout.cshtml";

    var intervals = System.Enum.GetValues(typeof(PlanInterval)).Cast<PlanInterval>().Select(value => new SelectListItem
                {
                    Text = value.ToString(),
                    Value = value.ToString()                
                });    
}
@section JsDocReady
{
    $("#mainForm").madValidate({
        rules:
        {
            "Id": "required"
        },
        useAjax: false
    });
}
@section Header
{
    <h1>@("New Account Plan")</h1>
}


    @Html.ValidationSummary()
    <form id="mainForm" method="post" action="@Url.Action("Create", "Staff_Plans")" class="form-horizontal">
        @Html.AntiForgeryToken()

        @Html.TextBoxControlGroupFor(m => m.Id)
        @Html.TextBoxControlGroupFor(m => m.Title)
        @Html.TextBoxControlGroupFor(m => m.Notes)
        @Html.TextBoxControlGroupFor(m => m.AssetsTotalSizeMax)
        @Html.TextBoxControlGroupFor(m => m.Price)
        @Html.ControlGroup(Html.ControlLabelFor(m=>m.AllowSignups), Html.CheckBoxFor(m =>m.AllowSignups))
        <div class="@Html.ControlGroupClass()">
            @Html.ControlLabelFor(m => m.BillingIntervalLength)
            @Html.ControlsWrapperBeginTag()
            @Html.TextBoxFor(m=> m.BillingIntervalLength)
            @Html.DropDownListFor(m => m.BillingIntervalUnit, intervals)
            @Html.ControlsWrapperEndTag()
        </div>
        <div class="@Html.ControlGroupClass()">
            @Html.ControlLabelFor(m => m.TrialIntervalLength)
            @Html.ControlsWrapperBeginTag()
            @Html.TextBoxFor(m=> m.TrialIntervalLength)
            @Html.DropDownListFor(m => m.TrialIntervalUnit, intervals)
            @Html.ControlsWrapperEndTag()
        </div>
        @Html.TextBoxControlGroupFor(m => m.VideosTotalMaxCount)
        @Html.TextBoxControlGroupFor(m => m.VideosPerBillingCycleMax)
        @Html.TextBoxControlGroupFor(m => m.VideoFileSizeMax)
        @Html.TextBoxControlGroupFor(m => m.VideoDurationLimit, "Max Video Duration (sec)")

        @Html.TextBoxControlGroupFor(m => m.ProductionLimit)
        @Html.TextBoxControlGroupFor(m => m.AssetFileSizeMax)
        @Html.TextBoxControlGroupFor(m => m.AssetsAllTimeMaxCount)
        @Html.TextBoxControlGroupFor(m => m.AssetsTotalMaxCount)
        @Html.TextBoxControlGroupFor(m => m.AssetsTotalSizeMax)

        @Html.FormButtons("Create")

    </form>

Takeoff.WebApp/Views/Staff_Plans/Details.cshtml
@model Staff_Plans_Plan
@{
    Layout = "~/Views/Staff/staff-layout.cshtml";
    ViewData["SubTitle"] = "Plans";
}
@section JsDocReady
{
    $("#delete").click(function()
    {
        if ( confirm('You sure you want to delete this?  No undo!') )
        {
            $("#deleteForm").submit();
        }
        return false;
    });
}

<div class="columnBg">
    <div class="columnBgHeader">
        <h3>New Account Plan</h3>
    </div>
    <div>
        <a href="/staff/plans">Plans</a> &nbsp; <a href="/staff/plans/edit?id=@Model.Id">Edit</a> &nbsp; <a href="#" id="delete">Delete</a>

        <form method="post" id="deleteForm" action="/staff/plans/delete?id=@Model.Id">
            @Html.AntiForgeryToken()        
        </form>
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.Id)
        @Html.DisplayTextFor(m => m.Id)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.Title)
        @Html.DisplayTextFor(m => m.Title)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.Notes)
        @Html.DisplayTextFor(m => m.Notes)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.Price)
        @Html.DisplayTextFor(m => m.Price)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.AllowSignups)
        @Html.DisplayTextFor(m => m.AllowSignups)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.BillingIntervalLength)
        @Html.DisplayTextFor(m => m.BillingIntervalLength)
        @Html.DisplayTextFor(m => m.BillingIntervalUnit)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.TrialIntervalLength)
        @Html.DisplayTextFor(m => m.TrialIntervalLength)
        @Html.DisplayTextFor(m => m.TrialIntervalUnit)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.VideosTotalMaxCount)
        @Html.DisplayTextFor(m => m.VideosTotalMaxCount)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.VideosPerBillingCycleMax)
        @Html.DisplayTextFor(m => m.VideosPerBillingCycleMax)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.VideoFileSizeMax)
        @Html.DisplayTextFor(m => m.VideoFileSizeMax)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.VideoDurationLimit, "Max Video Duration (sec)")
        @Html.DisplayTextFor(m => m.VideoDurationLimit)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.ProductionLimit)
        @Html.DisplayTextFor(m => m.ProductionLimit)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.AssetFileSizeMax)
        @Html.DisplayTextFor(m => m.AssetFileSizeMax)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.AssetsAllTimeMaxCount)
        @Html.DisplayTextFor(m => m.AssetsAllTimeMaxCount)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.AssetsTotalMaxCount)
        @Html.DisplayTextFor(m => m.AssetsTotalMaxCount)
    </div>
    <div class="formfield">
        @Html.LabelFor(m => m.AssetsTotalSizeMax)
        @Html.DisplayTextFor(m => m.AssetsTotalSizeMax)
    </div>
</div>

Takeoff.WebApp/Views/Staff_Plans/Edit.cshtml
@model Staff_Plans_Plan
@{
    Layout = "~/Views/Staff/staff-layout.cshtml";
    
    var intervals = System.Enum.GetValues(typeof(PlanInterval)).Cast<PlanInterval>().Select(value => new SelectListItem
                {
                    Text = value.ToString(),
                    Value = value.ToString()                
                });    
}
@section Header
{
    <h1>@("Plans")</h1>
}

@section JsDocReady
{
    $("#mainForm").madValidate({
        rules:
        {
            "Id": "required"
        },
        useAjax: false
    });
}
    @Html.ValidationSummary()
    <form id="mainForm" method="post" action="@Url.Action("Edit", "Staff_Plans")" class="form-horizontal">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m=>m.Id)
        @Html.TextBoxControlGroupFor(m => m.Id)
        @Html.TextBoxControlGroupFor(m => m.Title)
        @Html.TextBoxControlGroupFor(m => m.Notes)
        @Html.TextBoxControlGroupFor(m => m.Price)
        @Html.ControlGroup(Html.ControlLabelFor(m=>m.AllowSignups), Html.CheckBoxFor(m =>m.AllowSignups))
        <div class="@Html.ControlGroupClass()">
            @Html.ControlLabelFor(m => m.BillingIntervalLength)
            @Html.ControlsWrapperBeginTag()
            @Html.TextBoxFor(m=> m.BillingIntervalLength)
            @Html.DropDownListFor(m => m.BillingIntervalUnit, intervals)
            @Html.ControlsWrapperEndTag()
        </div>
        <div class="@Html.ControlGroupClass()">
            @Html.ControlLabelFor(m => m.TrialIntervalLength)
            @Html.ControlsWrapperBeginTag()
            @Html.TextBoxFor(m=> m.TrialIntervalLength)
            @Html.DropDownListFor(m => m.TrialIntervalUnit, intervals)
            @Html.ControlsWrapperEndTag()
        </div>
        @Html.TextBoxControlGroupFor(m => m.VideosTotalMaxCount)
        @Html.TextBoxControlGroupFor(m => m.VideosPerBillingCycleMax)
        @Html.TextBoxControlGroupFor(m => m.VideoFileSizeMax)
        @Html.TextBoxControlGroupFor(m => m.VideoDurationLimit, "Max Video Duration (sec)")
        @Html.TextBoxControlGroupFor(m => m.ProductionLimit)
        @Html.TextBoxControlGroupFor(m => m.AssetFileSizeMax)
        @Html.TextBoxControlGroupFor(m => m.AssetsAllTimeMaxCount)
        @Html.TextBoxControlGroupFor(m => m.AssetsTotalMaxCount)
        @Html.TextBoxControlGroupFor(m => m.AssetsTotalSizeMax)

        @Html.FormButtons("Update")
    </form>

Takeoff.WebApp/Views/Staff_Plans/Index.cshtml
@model IEnumerable<Takeoff.Data.IPlan>
@{
    Layout = "~/Views/Staff/staff-layout.cshtml";
}
@section Header
{
    <h1>@("Plans")</h1>
}
@section JsDocReady
{
}
@section CssInline
{
}
<p>Pricing Plans.</p><a href="/staff/plans/create">New</a>
    @if (!Model.HasItems())
    {   
        <p><strong>There aren't any.</strong></p>
    }
    else
    {
        <table id="membersList" cellspacing="0" class="data table table-striped">
            <thead>
                <tr>
                    <th>Id</th><th>Title</th><th>Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var plan in Model)
                {
                    <tr>
                        <td><a href="/staff/plans/details?id=@plan.Id">@plan.Id</a></td>
                        <td>@plan.Title</td>
                        <td>@(((double)plan.PriceInCents/100.0).ToString(NumberFormat.Currency))</td>
                    </tr>
                }
            </tbody>
        </table>
    
}

Takeoff.WebApp/Views/Staff_Plans/Sync.cshtml
@{
    Layout = "~/Views/Staff/staff-layout.cshtml";
    ViewData["SubTitle"] = "Plans";
}

    <p>This will update Recurly's plan database to match Takeoff's.  It might modify Recurly data.</p>
        <form id="mainForm" method="post" action="@Url.Action("Sync","Staff_Plans")">
            <div class="formfield actions">
                <input type="submit" value="Yes, I want to sync Recurly with Takeoff." />
            </div>
    </form>

Takeoff.WebApp/Views/Staff_Plans/SyncError.cshtml
@{
    Layout = "~/Views/Staff/staff-layout.cshtml";
    ViewData["SubTitle"] = "Plans";
}

    <div class="warning">The plan couldn't be synced.  You gotta fix that punk!  You can try to <a href="/staff/plans/sync">sync all plans</a> or just go back to <a href="/staff/plans">view all plans.</a></div>