Takeoff.WebApp/Models/ViewModels/Staff_Accounts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Mediascend.Web;
using Takeoff.Data;
using Takeoff.Models;

namespace Takeoff.ViewModels
{
    public class Staff_Accounts_Details
    {
        public int Id { get; set; }
        public IAccount Account { get; set; }
        public IUser Owner { get; set; }
        public string RecurlyUrl { get; set; }
    }

    public class Staff_Accounts_Edit
    {
        public int Id { get; set; }

        [DisplayName("Owner Id")]
        public int OwnerId { get; set; }

        [DisplayName("Account Plan")]
        public string PlanId { get; set; }

        [DisplayName("Account Status")]
        public AccountStatus Status { get; set; }

        [DisplayName("Trial Expiration")]
        public DateTime? TrialPeriodEndsOn { get; set; }

        [DisplayName("Current Billing Period Starts On")]
        public DateTime? CurrentBillingPeriodStartedOn { get; set; }

        

        public IEnumerable<SelectListItem> Plans
        {
            get
            {
                return Repos.Plans.Get().Select(p =>
                    {
                        return new SelectListItem
                        {
                            Value = p.Id,
                            Text = p.Title,
                        };
                    });
            }
        }

    }

}



Takeoff.WebApp/Controllers/Staff_AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Mediascend.Web;
using System.Web.Script.Serialization;
using System.Collections;
using Takeoff.Data;
using Takeoff.Models;
using Takeoff.Models.Data;
using System.Dynamic;
using MvcContrib;
using Takeoff.Transcoder;
using System.Configuration;
using Newtonsoft.Json.Linq;
using System.Web.UI.DataVisualization.Charting;
using System.Drawing;
using System.IO;
using System.Xml;
using System.Text;
using Takeoff.Resources;
using Recurly;
using System.Xml.Linq;
using Takeoff.ViewModels;
using System.Linq.Dynamic;
using System.ComponentModel;
using Takeoff.Data;

namespace Takeoff.Controllers
{
    [SpecialRestriction(SpecialRestriction.Staff)]
    [SubController("/staff/accounts", true)]
    public class Staff_AccountsController : BasicController
    {


        public ActionResult Index(DataTableParams dataTableParams)
        {
            ViewData["SectionTitle"] = "Accounts";

            using (var db = DataModel.ReadOnly)
            {
                var accounts = (from at in db.Things
                                join a in db.Accounts on at.Id equals a.ThingId
                                join ut in db.Things on at.CreatedByUserId equals ut.Id//todo: when you start tracking ownership, use that column instead.  also note this could create an orphaned record if the owner doesn't exist
                                join u in db.Users on ut.Id equals u.ThingId
                                where at.DeletedOn == null && at.Type == Things.ThingType(typeof(AccountThing)) && (a.Status != AccountStatus.Demo.ToString())
                                select new
                                {
                                    Id = at.Id,
                                    OwnerId = u.ThingId,
                                    Email = u.Email,
                                    u.Name,
                                    IsVerified = u.IsVerified,
                                    CreatedOn = at.CreatedOn,
                                    a.Status,
                                    Plan = a.PlanId,
                                    FileCount = (from t in db.Things
                                                      join f in db.Files on t.Id equals f.ThingId
                                                      where (f.IsSample == null || !f.IsSample.Value) && t.DeletedOn == null && f.DeletePhysicalFile && t.Type == Things.ThingType(typeof(FileThing)) && t.AccountId == at.Id
                                                      select f).Count(),
                                    FileSize = (from t in db.Things
                                                     join f in db.Files on t.Id equals f.ThingId
                                                     where (f.IsSample == null || !f.IsSample.Value) && t.DeletedOn == null && f.DeletePhysicalFile && f.Bytes.HasValue && t.Type == Things.ThingType(typeof(FileThing)) && t.AccountId == at.Id
                                                     select (long?)f.Bytes).Sum().GetValueOrDefault(),
                                    VideoCount = (from t in db.Things
                                                  join v in db.Videos on t.Id equals v.ThingId
                                                  where (v.IsSample == null || !v.IsSample.Value) && t.DeletedOn == null && t.AccountId == at.Id && t.Type == Things.ThingType(typeof(VideoThing))
                                                  select t).Count(),
                                    VideoDuration = (from t in db.Things
                                                     join v in db.Videos on t.Id equals v.ThingId
                                                     where (v.IsSample == null || !v.IsSample.Value) && t.DeletedOn == null && t.AccountId == at.Id && v.Duration.HasValue && t.Type == Things.ThingType(typeof(VideoThing))
                                                     select (long?)v.Duration).Sum().GetValueOrDefault(),
                                    VideoStreamCount = (from t in db.Things
                                                        join f in db.Files on t.Id equals f.ThingId
                                                        where (f.IsSample == null || !f.IsSample.Value) && t.DeletedOn == null && t.AccountId == at.Id && t.Type == Things.ThingType(typeof(VideoStreamThing))
                                                        select t).Count(),
                                    VideoStreamSize = (from t in db.Things
                                                       join f in db.Files on t.Id equals f.ThingId
                                                       where (f.IsSample == null || !f.IsSample.Value) && t.DeletedOn == null && t.AccountId == at.Id && f.DeletePhysicalFile && f.Bytes.HasValue && t.Type == Things.ThingType(typeof(VideoStreamThing))
                                                       select (long?)f.Bytes).Sum().GetValueOrDefault(),
                                    DownloadSize = (from ft in db.FileDownloadLogs
                                                    where ft.AccountId == at.Id
                                                    select (long?)ft.Bytes).Sum().GetValueOrDefault(),
                                    DownloadCount = (from ft in db.FileDownloadLogs
                                                     where ft.AccountId == at.Id
                                                     select ft).Count(),
                                    UploadSize = (from ft in db.FileUploadLogs
                                                  where ft.AccountId == at.Id
                                                  select (long?)ft.Bytes).Sum().GetValueOrDefault(),
                                    UploadCount = (from ft in db.FileUploadLogs
                                                   where ft.AccountId == at.Id
                                                   select ft).Count(),
                                    ProjectCount = (from t in db.Things where t.DeletedOn == null && t.Type == Things.ThingType(typeof(ProjectThing)) && t.AccountId == at.Id select t).Count(),
                                    MemberCount = (from t in db.Things where t.DeletedOn == null && t.Type == Things.ThingType(typeof(AccountMembershipThing)) && t.AccountId == at.Id select t).Count(),
                                });

                if (this.Request.IsAjaxRequest())
                {
                    var response = new DataTableResponse();
                    if (dataTableParams.SortBy.HasItems())
                    {
                        accounts = accounts.OrderBy(string.Join(",", dataTableParams.SortBy));
                    }

                    response.iTotalRecords = accounts.Count();
                    if (dataTableParams.Search.HasChars())
                    {
                        var search = dataTableParams.Search;
                        accounts = accounts.Where(u => u.Email.Contains(search) || u.Name.Contains(search) || u.Plan.Contains(dataTableParams.Search) || u.Status.Contains(dataTableParams.Search));
                        response.iTotalDisplayRecords = accounts.Count();
                    }
                    else
                    {
                        response.iTotalDisplayRecords = response.iTotalRecords;
                    }
                    if (dataTableParams.DisplayLength > 0)
                    {
                        accounts = accounts.Skip(dataTableParams.DisplayStart).Take(dataTableParams.DisplayLength);
                    }
                    var data = accounts.ToArray();
                    //var accountThings = accounts.Select(a => Things.GetOrNull<AccountThing>(a.Id));

                    response.sEcho = dataTableParams.Echo;
                    response.aaData = data.Select(record =>
                    {
                        return new
                        {
                            record.Id,
                            record.OwnerId,
                            record.Plan,
                            CreatedOn = record.CreatedOn.ForJavascript(),
                            record.Name,
                            record.Status,
                            Email = record.Email,
                            IsVerified = record.IsVerified,
                            record.ProjectCount,
                            record.VideoCount,
                            record.VideoDuration,
                            record.VideoStreamCount,
                            record.VideoStreamSize,
                            record.FileCount,
                            record.FileSize,
                            record.UploadCount,
                            record.UploadSize,
                            record.DownloadCount,
                            record.DownloadSize,
                            record.MemberCount,
                        };
                    }).ToArray();
                    return Json(response);
                }
            }
            return View();
        }

        /// <summary>
        /// Show owner details, plan, expiration shit, clear thing cache, impersonate
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            var accountThing = Things.Get<AccountThing>(id);
            return View(new Staff_Accounts_Details
                            {
                                Id = id,
                                Account = accountThing,
                                RecurlyUrl = "https://{0}.recurly.com/accounts/{1}".FormatString(Recurly.Configuration.RecurlySection.Current.Subdomain, id),

Takeoff.WebApp/Views/Staff_Accounts/Delete.cshtml

@{
    Layout = "~/Views/Staff/staff-layout.cshtml";
    ViewData["SubTitle"] = "Delete Account #" + @ViewBag.Id;
}

	<h1>@("Delete Account")</h1>
<p class="@Html.AlertWarningClass()">There is no undo!</p>
        <form method="post" action="@Url.Action("Delete", "Staff_Accounts", new { id = ViewBag.Id })" class="form-horizontal">
            @Html.ControlGroup(Html.ControlLabel("Delete User Also"), Html.CheckBox("deleteUser"))
            <div class="@Html.FormActionsClass()">
                <input class="btn btn-danger" value="@("Delete Account ")" type="submit" />
            </div>
        </form>

Takeoff.WebApp/Views/Staff_Accounts/Details.cshtml
@model Staff_Accounts_Details
@{
    Layout = "~/Views/Staff/staff-layout.cshtml";
}
@section Header
{
    <h1>@("Account #") @Model.Id</h1>
}

@section JsDocReady
{
$("#impersonate").click(function (e) {
    var message = "Do you want to log in as this account owner?  You will be able to do everything they can do.  If you want to come back to the staff section you'll have to log out then back in under your normal account.  Remember impersonating is not an excuse for spying.";
    if (!confirm(message)) {
        e.preventDefault();
        return false;
    }
});
}
@section CssInline
{
}
<div>
<a href="@Url.Action("Edit", "Staff_Accounts", Model.Id)">Edit Account</a> &nbsp; <a href="@Url.Action("Delete", "Staff_Accounts", Model.Id)">Delete Account</a>
</div>
<div>
    <label>Owner:</label>
    @Model.Owner.DisplayName &nbsp; <a href="mailto:@Model.Owner.Email">@Model.Owner.Email</a> &nbsp; <a href="@Url.ActionDetails("Staff_Users",Model.Owner.Id)">View/Edit User Details</a> &nbsp; <a id="impersonate" href="@Url.Action("Impersonate","Staff_Users", new { id = Model.Owner.Id })">Impersonate</a>
</div>
@if (Model.Account.IsSubscribed())
{
<div>
    <label>Recurly Link:</label>
    <a href="@Model.RecurlyUrl" target="_blank">View Account in Recurly</a>
</div>
}
<div>
    <label>Account Status:</label>
    @Model.Account.Status
</div>
<div>
    <label>Plan:</label>
@if ( Model.Account.Plan == null )
{
    <span>NONE!</span>
}
else
{
   @Model.Account.Plan.Id
}
</div>
<div>
    <label>Created:</label>
    @Model.Account.CreatedOn
</div>

@if ( Model.Account.CurrentBillingPeriodStartedOn.HasValue )
{
<div>
    <label>Current Billing Period Started On:</label>
    @Model.Account.CurrentBillingPeriodStartedOn.Value.ToString(DateTimeFormat.ShortDateTime)
</div>
}

@if ( Model.Account.CurrentBillingPeriodEndsOn().HasValue )
{
<div>
    <label>Current Billing Period Ends On:</label>
    @Model.Account.CurrentBillingPeriodEndsOn().Value.ToString(DateTimeFormat.ShortDateTime)
</div>
}


<div>
<label>Trial Period Ends:</label>
@if (!Model.Account.TrialPeriodEndsOn.HasValue)
{
    <span>N/A</span>
}
else
{
    <span>@Model.Account.TrialPeriodEndsOn - @Model.Account.DaysLeftInTrial days left</span>
}
</div>




<div>
    <label>Productions:</label>
    @Model.Account.ProductionCount
</div>
<div>
    <label>Videos Total:</label>
    @Model.Account.VideoCount
</div>
<div>
    <label>Videos In Billing Cycle:</label>
    @Model.Account.VideosAddedInBillingCycle
</div>
@*<div>
    <label>Video Stats:</label>
    @Model.VideoCount videos totaling @((int)TimeSpan.FromSeconds((double)Model.VideoDuration).TotalMinutes) mintues,  @Model.VideoStreamCount Video Files totaling @(new FileSize((long)Model.VideoStreamSize))
</div>
<div>
    <label>Asset Files:</label>
    @Model.AssetFileCount files totaling @(new FileSize((long)Model.AssetFileSize))
</div>
<div>
    <label>Downloads:</label>
    @Model.DownloadCount files totaling @(new FileSize((long)Model.DownloadSize))
</div>
<div>
    <label>Uploads:</label>
    @Model.UploadCount files totaling @(new FileSize((long)Model.UploadSize))
</div>
*@


Takeoff.WebApp/Views/Staff_Accounts/Edit.cshtml
@model Staff_Accounts_Edit
@{
    Layout = "~/Views/Staff/staff-layout.cshtml";
}
@section Header
{
<h1>@("Account #") @Model.Id</h1>
}
@Html.ValidationSummary("Please address the following:")
<form id="mainForm" method="post" action="@Url.Action("Edit", "Staff_Accounts")" class="form-horizontal">
@Html.AntiForgeryToken()
    <fieldset>
        @Html.TextBoxControlGroupFor(m => m.OwnerId)
        @Html.ControlGroup(Html.ControlLabelFor(m => m.PlanId), Html.DropDownListFor(m => m.PlanId, Model.Plans))
        @Html.ControlGroup(Html.ControlLabelFor(m => m.Status), Html.DropDownListFor(m => m.Status, typeof(AccountStatus).SelectItems()))
        @Html.TextBoxControlGroupFor(m => m.TrialPeriodEndsOn)
        @Html.TextBoxControlGroupFor(m => m.CurrentBillingPeriodStartedOn)
        @Html.FormButtons("Update")
    </fieldset>
</form>

Takeoff.WebApp/Views/Staff_Accounts/Index.cshtml
@{
    Layout = "~/Views/Staff/staff-layout.cshtml";
    ViewData["SubTitle"] = "Accounts";
}

@section JsDocReady
{
pageAccounts();
}
@section Header
{
<h1>Accounts</h1>
}

<p>Excludes demo accounts.</p>
<table cellspacing="0" id="dataTable" class="data table table-striped">
    <thead>
    </thead>
    <tbody>
     </tbody>
</table>
